title: FarmBot Software Development Documentation
url: https://developer.farm.bot
description: Documentation for 3rd-party developers to work with the FarmBot API
logo: /assets/images/documentation.png
remote_theme: FarmBot-Docs/farmbot-theme@main
baseurl: /
color: '#0c4d8a'
latest_version_number: 15
plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
include:
  - _images
  - _redirects
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
algolia:
  application_id: Z1MM044EZ8
  index_name: developers
  search_only_api_key: cad8ec927860485f3a8ac1ce2372be28
  nodes_to_index: 'p,table,h1'
  max_record_size: 20000
  files_to_exclude:
    - index.md
    - v6/**/*
    - v7/**/*
    - v8/**/*
    - v9/**/*
    - v10/**/*
    - v11/**/*
    - v12/**/*
    - v13/**/*
